version: '2'

services:

  user_service:
    build:
      context: .
      dockerfile: ./docker/user_service/Dockerfile
    container_name: user_service
    networks:
      - overlay
    ports:
      - "8000:8000"

  agent:
    build:
      context: .
      dockerfile: ./docker/agent/Dockerfile
    
    container_name: bandit_agent
    networks:
      - overlay
    ports:
      - "8001:8001"  
    
    depends_on:
      - user_service

networks:
  overlay: {}