0:
  mean: 0.5
  sigma: 1

1:
  mean: 0.5
  sigma: 1.5

2: 
  mean: 4
  sigma: 0.5

3:
  mean: 2
  sigma: 0.1

4:
  mean: 2
  sigma: 1.0

5:
  mean: 5
  sigma: 0.2

6:
  mean: 1
  sigma: 1

7:
  mean: 0.2
  sigma: 1.5

8: 
  mean: 3
  sigma: 0.2

9:
  mean: 2.5
  sigma: 1.5
